# Generated by Django 5.2.6 on 2025-09-09 22:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jerseys', 'Jerseys'), ('boots', 'Football Boots'), ('training', 'Training Gear'), ('accessories', 'Accessories'), ('equipment', 'Equipment'), ('merchandise', 'Club Merchandise'), ('collectibles', 'Collectibles'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
